### ISSUE TITLE
Button states do not get updates by PyQT updates

### ISSUE THREAD

**Issue by basvandriel** [minvws/nl-uzipoc-yubisign#35]
Currently in a `QWizardPage`, we are disabling and enabling buttons with the following code snippet:

```python
self.wizard().button(QWizard.WizardButton.NextButton).setEnabled(False)
```

This does however not work in the page initialization. When you add this to the first line of an `initializePage` method, it won't get disabled. The same goes for changing the text. See the example below, running on PyQt6  version `6.7.1` and Python `3.13`.:

```python
import sys

from PyQt6.QtWidgets import (
    QWidget,
    QApplication,
    QWizard,
    QWizardPage,
    QVBoxLayout,
    QLabel,
)
from PyQt6.QtCore import QTimer


app = QApplication(sys.argv)

wizard = QWizard()
wizard.addPage(Page1())
wizard.addPage(Page2())

wizard.show()

app.exec()


class Page1(QWizardPage):
    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.setTitle("page 1")
        layout = QVBoxLayout(self)
        label = QLabel("pages")
        layout.addWidget(label)

        self.setLayout(layout)


class Page2(QWizardPage):
    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.setTitle("Page2")
        layout = QVBoxLayout(self)
        label = QLabel("Page2")
        layout.addWidget(label)
        self.setLayout(layout)

    def initializePage(self):
        super().initializePage()
        self._disable_backbutton()

    def _disable_backbutton(self):
        button = self.wizard().button(QWizard.WizardButton.BackButton)
        button.setEnabled(False)

```

The reason for this is still unknown, but I'm assuming that the `QWizard` handles its own page navigation internally and therefor also the state of its buttons. I did find a workaround for this, and that is delaying the method call by using`QTimer.singleShot(0, self._disable_backbutton)`.

The problem is also, `PyQt6` doesn't seem to be open source or doesn't have any documentation on contributing to the product. This makes it hard to investigate what the underlying problem is.

**Comment by basvandriel** [comment]
My bad - I was looking for the `pyqt6` install, not looking for the C libraries.

**Comment by ricklambrechts** [comment]
Fixed with https://github.com/minvws/nl-uzipoc-yubisign/pull/37
