### ISSUE TITLE
Error when trying to find the `libykcs11.dll` file on Windows

### ISSUE THREAD

**Issue by basvandriel** [minvws/nl-uzipoc-yubisign#45]
Using the `PKCS11LibFinder` class, the unerneath error is raised when the library is loaded.

```bash
LoadLibrary() failed with error 126: The specified module could not be found.
```

The file path exists and is parseable from Python. Even with the below snippet, there are no errors.

```python
import ctypes

dll_path = r"C:\Program Files\Yubico\Yubico PIV Tool\bin\libykcs11.dll"
try:
    my_dll = ctypes.CDLL(dll_path)
    print("DLL loaded successfully!")
except OSError as e:
    print(f"Failed to load DLL: {e}")
```

This issue specifically occurs on @ScrumServices computer'. When @ricklambrechts tries the same on a Windows machine, the error is not raised. Both @ricklambrechts  and @ScrumServices' computer are on python `3.13.1` and pykcs11 version `1.5.17`.

**Comment by ricklambrechts** [comment]
Fixed by #46
